more debug echos

diff --git a/components/provisioning/warewulf-provision/SOURCES/warewulf-provision.mkbootable.patch b/components/provisioning/warewulf-provision/SOURCES/warewulf-provision.mkbootable.patch
--- a/components/provisioning/warewulf-provision/SOURCES/warewulf-provision.mkbootable.patch
+++ b/components/provisioning/warewulf-provision/SOURCES/warewulf-provision.mkbootable.patch
@@ -1,5 +1,5 @@
 --- warewulf-provision-3.6/initramfs/capabilities/setup-filesystems/80-mkbootable	2014-05-21 11:13:01.000000000 -0700
-+++ warewulf-provision-3.6.patch/initramfs/capabilities/setup-filesystems/80-mkbootable	2016-03-29 08:49:01.000000000 -0700
++++ warewulf-provision-3.6.patch/initramfs/capabilities/setup-filesystems/80-mkbootable	2016-03-29 11:40:31.000000000 -0700
 @@ -20,6 +20,9 @@
              if [ -x "$NEWROOT/sbin/dracut" ]; then
                  chroot $NEWROOT /sbin/dracut --force '' $KERNELVERSION
@@ -10,7 +10,7 @@
              elif [ -x "$NEWROOT/sbin/mkinitrd" ]; then
                  INITRD=`cd $NEWROOT; find boot/initr*-${KERNELVERSION}.img* 2>/dev/null | tail -n 1`
                  if [ -n "$INITRD" ]; then
-@@ -29,10 +32,53 @@
+@@ -29,10 +32,58 @@
                  chroot $NEWROOT /sbin/mkinitrd -f $INITRD $KERNELVERSION
                  umount $NEWROOT/sys
              fi
@@ -49,13 +49,18 @@
 +                        echo "GRUB_SERIAL_COMMAND='serial --speed=${SERIALSPEED} --unit=${SERIALUNIT} --word=${SERIALWORD} --parity=${SERIALPARITY}'" >> $NEWROOT/etc/default/grub
 +                    fi
 +                else
++                    echo "#WAREWULF Addition" >> $NEWROOT/etc/default/grub
 +                    echo "GRUB_CMDLINE_LINUX='${WWKARGS}'" >> $NEWROOT/etc/default/grub
 +                fi                    
 +                if chroot $NEWROOT /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg >/dev/null
 +                    echo "grub2-mkconfig completed successfully."
++                else 
++                    echo "grub2-mkconfig failed."
++                    exit 255
 +                fi
  
 +                if chroot $NEWROOT /usr/sbin/grub2-install $WWBOOTLOADER >/dev/null; then
++                    echo "grub2-install completed successfully."
 +                    exit 0
 +                else 
 +                    echo "grub2-install failed."
@@ -66,7 +71,7 @@
                  if [ -n "$INITRD" -a -n "$KERNEL" ]; then
                      if [ -f "$NEWROOT/etc/redhat-release" ]; then
                          OSVERSION=`sed -e 's@ (.*@@' $NEWROOT/etc/redhat-release`
-@@ -47,21 +93,22 @@
+@@ -47,21 +98,22 @@
                              KERNEL=${KERNEL##boot/}
                          fi
                      fi
