fix error printing in case no search path was provided
Signed-off-by: Götz Waschk <goetz.waschk@desy.de>

diff --git a/components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires b/components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires
--- a/components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires
+++ b/components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires
@@ -28,7 +28,7 @@ fi
 searchPath="$2"
 
 if [ -z "$searchPath" ];then
-    >&2echo "Required search path argument not provided"
+    >&2 echo "Required search path argument not provided"
     exit 1
 fi
 
